-- Enable generation of UUIDs for primary keys
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: subjects
-- Represents the courses the student is enrolled in for the 4.5-month semester.
CREATE TABLE subjects (
    subject_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    course_code VARCHAR(20) NOT NULL,
    course_name VARCHAR(255) NOT NULL,
    lectures_per_week INT DEFAULT 3,
    tutorials_per_week INT DEFAULT 1,
    labs_per_week INT DEFAULT 1,
    midterm_week INT DEFAULT 8,
    final_week INT DEFAULT 16,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: topics
-- Represents the structured JSON list of topics extracted from the course handout.
CREATE TABLE topics (
    topic_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    subject_id UUID NOT NULL REFERENCES subjects(subject_id) ON DELETE CASCADE,
    topic_name VARCHAR(500) NOT NULL,
    assigned_week INT NOT NULL CHECK (assigned_week BETWEEN 1 AND 18),
    estimated_lecture_count INT DEFAULT 3,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: micro_tasks
-- Stores the discrete actionable study items generated by the Claude API.
CREATE TABLE micro_tasks (
    task_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    topic_id UUID NOT NULL REFERENCES topics(topic_id) ON DELETE CASCADE,
    task_title VARCHAR(500) NOT NULL,
    action_verb VARCHAR(50) NOT NULL, 
    estimated_duration_mins INT NOT NULL CHECK (estimated_duration_mins BETWEEN 30 AND 60),
    base_difficulty DECIMAL(3,2) DEFAULT 1.00, 
    is_exam_prep BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: weekly_goals
-- Represents the temporal buckets into which micro_tasks are packaged.
CREATE TABLE weekly_goals (
    goal_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    semester_week_number INT NOT NULL CHECK (semester_week_number BETWEEN 1 AND 18),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_capacity_mins INT DEFAULT 1200, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: task_status
-- A state-tracking table linking tasks to weekly goals. Manages the rollover lifecycle.
CREATE TABLE task_status (
    status_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID NOT NULL REFERENCES micro_tasks(task_id) ON DELETE CASCADE,
    goal_id UUID NOT NULL REFERENCES weekly_goals(goal_id) ON DELETE CASCADE,
    current_status VARCHAR(50) NOT NULL DEFAULT 'pending', 
    rollover_count INT DEFAULT 0,
    dynamic_priority_score DECIMAL(10,4) DEFAULT 0.0000,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_task_goal UNIQUE (task_id, goal_id)
);

-- Partial index to instantly fetch active pending tasks for the weekly bucket.
-- Prevents the index from growing linearly as historical tasks accumulate.
CREATE INDEX idx_active_pending_tasks 
ON task_status (goal_id, dynamic_priority_score DESC) 
WHERE current_status = 'pending';

-- Index to support rapid aggregation of topics by subject and week
CREATE INDEX idx_topics_subject_week 
ON topics (subject_id, assigned_week);
